# Generated by Django 2.2.7 on 2020-03-31 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200331_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='institution',
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Institution'),
        ),
    ]
