# Generated by Django 2.2.7 on 2020-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200331_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='institution',
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ManyToManyField(to='main_app.Institution'),
        ),
    ]
