# Generated by Django 2.2.7 on 2020-03-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_donation_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='collected',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
