# Generated by Django 2.2.7 on 2020-03-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200331_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='collected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(0, 'Fundacja'), (1, 'Organizacja pozarządowa'), (2, 'Zbiórka lokalna')], default=0),
        ),
    ]
